apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensorflow-model-server
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: tensorflow-model-server
    spec:
      containers:
      - name: tensorflow-model-server
        image: path/to/your/tensorflow-model-server:latest
        command:
        - /bin/sh
        - -c
        args:
        - tensorflow_model_server --port=9000 --model_config_file=/tmp/models.conf
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tensorflow-model-service
  name: tensorflow-model-service
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: tensorflow-model-server
  type: LoadBalancer
